### ISSUE TITLE
Build-from-source fails on UE 5.8 CL 55116800 — 2 MonolithKeyToString() sites missed (FJsonObject FSharedString keys)

### ISSUE THREAD

**Issue by Baba-Ramsi** [tumourlove/monolith#80]
### Summary
On a UE **5.8.0 (CL 55116800)** C++ project building Monolith **v0.20.3 (UE5.8)** from source, compilation of `MonolithAnimation` fails. Two call sites iterate `FJsonObject::Values` and use the key as an `FString` without going through the `MonolithKeyToString()` shim. On this 5.8 changelist, `FJsonObject::Values` keys are `UE::FSharedString` (`UE_JSONOBJECT_LEGACY_STRING_KEYS` off; `FStringType = UE::FSharedString`), which has no implicit conversion to `FString`.

The helper already exists (`MonolithCore/Public/MonolithJsonUtils.h`) and is used correctly almost everywhere — these two are just misses. All 19 other modules compile clean.

### Environment
- UE **5.8.0**, `++UE5+Release-5.8-CL-55116800` (Epic Launcher binary engine)
- MSVC 14.44.35227 toolchain, Windows SDK 10.0.22621.0
- Monolith **v0.20.3**, `Monolith-v0.20.3-UE5.8.zip`, built from source (C++ project full rebuild)

### Error
```
MonolithChooserActions.cpp(547): error C2664: ... cannot convert argument 1
  from 'const T' to 'const FString &'
  with [ T=UE::JSON::Private::FJsonObjectSharedStringStorage::FStringType ]
```

### The two sites + fix

**1. `MonolithAnimation/Private/MonolithChooserActions.cpp:547`**
```diff
-            Remap.Add(NormalizePackagePath(Pair.Key), Val);
+            Remap.Add(NormalizePackagePath(MonolithKeyToString(Pair.Key)), Val);
```
(also needs `#include "MonolithJsonUtils.h"`)

**2. `MonolithAnimation/Private/MonolithSkeletonRetargetActions.cpp:580`**
```diff
-        for (const TPair<FString, TSharedPtr<FJsonValue>>& Pair : SettingsObj->Values)
-        {
-            const FString& FieldName = Pair.Key;
+        for (const auto& Pair : SettingsObj->Values)
+        {
+            const FString FieldName = MonolithKeyToString(Pair.Key);
```
(also needs `#include "MonolithJsonUtils.h"`)

With both applied, the full rebuild succeeds and the editor loads Monolith 0.20.3 normally. Likely the UE5.8 prebuilt binaries were produced against an earlier 5.8 CL where `Values` was still `FString`-keyed, so the misses didn't surface in CI.

Thanks for the great tool!

**Comment by tumourlove** [comment]
Fixed in v0.21.0. Both MonolithAnimation sites now go through the `MonolithKeyToString` shim, so the same source compiles on UE 5.7 (FString keys) and 5.8 CL 55116800 (FSharedString keys) — including the hard-typed TPair loop in MonolithSkeletonRetargetActions. Thanks for the pinpoint report and the exact fix, @Baba-Ramsi (and @dulanw for the parallel PR #79). https://github.com/tumourlove/monolith/releases/tag/v0.21.0
